spring:
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2.console.enabled: true

  data.rest:
    basePath: /api
    defaultPageSize: 20
    returnBodyOnCreate: true

logging:
  level:
    root: WARN
    ru.javaops.restaurant_voting: DEBUG

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

server:
  error:
    whitelabel:
      enabled: false


